### ISSUE TITLE
ValueError: 'keyword' has not been learned by the model so it cannot be Searched

### ISSUE THREAD

**Issue by dkamalakar** [ddangelov/Top2Vec#112]
I understand why the error is coming. But seems like counter intuitive if only learned topics/keywords can be searched and returned . A better implementation may be to return probability of the match with keyword being searched.....I am using doc2vec so not sure if other implementations behave the same way......thoughts ?

**Comment by ddangelov** [comment]
With `embedding_model` set to `doc2vec` you cannot search with keywords that have not been learned by the model. A way to make sure all words in the corpus are learned is by setting lowering the `min_count` parameter. Have a look at the [Top2Vec API](https://top2vec.readthedocs.io/en/latest/api.html).

With `embedding_model` set to the other options it is possible to search with any keyword since those are pre-trained models. This will be available in the future.

**Comment by firmai** [comment]
hey, just popping in to see how this is progressing:

'''With embedding_model set to the other options it is possible to search with any keyword since those are pre-trained models. This will be available in the future.'''

**Comment by patilsumeetv** [comment]
**ValueError: 'keyword' has not been learned by the model so it cannot be Searched**
This error still persists even after training with pre-trained models like USE, any solution for this??
