### ISSUE TITLE
Fixed number of Topics

### ISSUE THREAD

**Issue by karthikraja95** [ddangelov/Top2Vec#210]
Is there a way to get fixed number of topics? I know topic2vec is using other techniques to find the number of topics automatically, just wondering if there is a way to get fixed number of topics, because every time I run topic2vec, it gives different number of topics? Maybe is there a random seed that I can use to get the same results every time I run the model?

**Comment by sean-doody** [comment]
It's because the UMAP embedding is stochastic. You can set a random seed for UMAP by adding UMAP parameters in a dictionary, and HBSCAN should find the same number of clusters each time:

```python
umap_args = {"random_state": 42}
```

You can also use the `hierarchical_topic_reduction()` method to reduce a trained model to the desired number of topics.

**Comment by karthikraja95** [comment]
Thanks for the quick reply @sean-doody. I will try it out

**Comment by ddangelov** [comment]
You can use ` hierarchical_topic_reduction` to reduce to a fixed number of topics.
