### ISSUE TITLE
Embedding from pre-trained are poor on domain-specific corpus?

### ISSUE THREAD

**Issue by travishsu** [ddangelov/Top2Vec#251]
I have a very domain-specific (patent-related) corpus, length of each documents ranges from 522 to 4136, following are the 2D visualization of UMAP:

- `universal-sentence-encoder`
  ![umap_universal-sentence-encoder](https://user-images.githubusercontent.com/4914984/159214513-0e9d42e6-f521-48e0-b336-9e2e206be186.png)
- `paraphrase-multilingual-MiniLM-L12-v2`
  ![umap_paraphrase-multilingual-MiniLM-L12-v2](https://user-images.githubusercontent.com/4914984/159214569-efa579a5-bf75-47a7-933a-d3e2e262ede2.png)
- `doc2vec`
  ![umap_doc2vec](https://user-images.githubusercontent.com/4914984/159215748-1a59d67f-d4d3-46e5-ab6a-95cf34e92e0a.png)

```python
umap_args = {
    'n_neighbors': 15,
    'n_components': 5,
    'metric': 'cosine'}
hdbscan_args = {
    'min_cluster_size': 15,
    'metric': 'euclidean',
    'cluster_selection_method': 'eom'}
```

Can I interpret this that pre-trained embedding are bad because my corpus is too domain-specific?

**Comment by travishsu** [comment]
BTW, while using `doc2vec` embedding, can I fetch the terms in the center of embedding space?

That seems to be some redundent words and informative to no documents almost, I would like to add them to my custom stop-words.

![umap_doc2vec](https://user-images.githubusercontent.com/4914984/159216896-2e77f594-8de0-4be8-94e8-4a17ccf1ebd9.png)

**Comment by ddangelov** [comment]
Which topics were better? What made you think the embeddings are poor other than the vocab being distant from the documents?

**Comment by travishsu** [comment]
I want to extract some technical terms (such as LDD) in patent documents about semiconductors and doc2vec performs this well. When I used pre-trained embedding, topic words were semiconductor, conductor, chip.

**Comment by sean-doody** [comment]
@travishsu It's because your corpus specific vocabulary is not present in the vocabulary of the pre-trained models. The `doc2vec` model learns both document embeddings *and* word embeddings from your data itself: that's why you see those corpus-specific terms. You should use `doc2vec` if you want your corpus-specific vocabulary, though in my experience, `doc2vec` results in worse clustering (i.e., a much larger proportion of documents will be classified as noise by HDBSCAN, and Top2Vec will reassign them after the fact to their most similar topic vector). Another option is to use something like [C-TF-IDF](https://maartengr.github.io/BERTopic/api/ctfidf.html) to extract your corpus-specific vocabulary when using pre-trained models.

**Comment by travishsu** [comment]
Ok, noted with thx.
