### ISSUE TITLE
Way of increasing number of topics?

### ISSUE THREAD

**Issue by jessicajhassibi** [ddangelov/Top2Vec#277]
Hello, 
I am using Top2Vec for my bachelors thesis. My data are around 1500 Wikipedia article texts in different languages about persecuted music composers in the era of national socialism in germany. I only get 2 topics, one being about countries, the other about "music", "music composers" etc.
Is there a way to get more topics or more fine-grained topics? 
I am expecting results like "jewish", "war", "national socialism" and so on.
Thanks for the help!

**Comment by sean-doody** [comment]
Are you using pre-trained embedding models or **doc2vec**? If you're using pre-trained models, they are going to truncate your articles after ***N*** tokens. This will affect how the model performs. Since you're dealing with a small sample of presumably long Wiki articles, I'd even consider breaking the articles into separate documents at the paragraph level.

In general, you can get more clusters by reducing the **min_cluster_size** and **min_samples** parameters in HDBSCAN. Do keep in mind that shrinking **min_cluster_size** will usually result in more documents being assigned as noise. Also,if you're using **doc2vec**, I have found that **doc2vec** embeddings generate the most noise at cluster time.

Top2Vec reclassifies all noise documents to their most similar cluster, but having large amounts of noise is not ideal for topical coherence.

**Comment by wjbmattingly** [comment]
I agree with everything @sean-doody has said. I am just posting here for a reply I gave to another issue that may give you some extra clarity on how the clustering process works:

https://github.com/ddangelov/Top2Vec/issues/291

**Comment by ddangelov** [comment]
In general to increase number of topics some possible strategies are to increase the number of documents, split the documents into smaller chunks, or change the `HDBSCAN` parameter `n_neighbors` from 15 to a smaller number.

**Comment by sickofhoneysuckle** [comment]
@ddangelov quick question. How does one change the paramenters for HDBSCAN? Im not seeing number of neighbors as an argument for HDBSCAN on its doc page (I do see it for UMAP however).  Also what is the syntax for that, if you don't mind me asking? I'm struggling with a similar issue to @jessicajhassibi (down the undergrad thesis project haha).  Also when you said chunk the data beforehand, do you simply mean using the top2vec chunker or preprocess the data beforehand into a new set of documents.
