### ISSUE TITLE
[Feature Request] Possible to include dendrogram visualizations?

### ISSUE THREAD

**Issue by wfkwan** [ddangelov/Top2Vec#46]
The project is awesome and the API is well documented! Top2Vec would automatically identity the number of topics since it uses HDBSCAN. In my application 1970 topics are generated are this is really too much to interpret. Then I go for using hierarchical topic reduction but then the choice of number of topics to reduced is not intuitive to decide. So I would like to ask if a dendrogram plot feature can be added?

**Comment by ddangelov** [comment]
The number of topics to choose for hierarchical reduction should be a number that you find reasonable to look through. The smaller the number, the more high level the topics will be. Since there is a hierarchy each reduced topic will also give you the original topic that formed it. 

Perhaps a dendrogram plot feature will be added in the future. There are some plans to add more functionality to the hierarchical reduction.

**Comment by wfkwan** [comment]
Thanks, I simply thought that the sometimes the range of "reasonable" values for number of topics is quite vague. Perhaps some visualization tools can help to have an impression on how the documents are distributed in space after reduction. Looking forward to your new functionality!
