### ISSUE TITLE
Some features request

### ISSUE THREAD

**Issue by Benja1972** [ddangelov/Top2Vec#5]
Thank you for nice end elegant approach to topic modeling. I would propose to implement few features. 

- In many topic model we can infer topic distribution on unseen document. I suppose it is possible to do also in your framework
- Doc2vec and word2vec of gensim is online in terms of adding new documents to model without retraining whole corpus. Would be nice to have it implemented in Top2vec, and see how new documents affect extracted topics (topic drift, birth, death etc.)
- In HDBSCAN there is parameter of min_cluster_size which affect number of extracted topics. Would be nice to have ability to control it  in __init__ function of class. It can serve as concentration parameter of classical topic models. 

Good luck and thank you again!

**Comment by ddangelov** [comment]
Hi Benja,

Thank you for reaching out.

Inferring topics of unseen documents and adding them to the model is on the to-do list. Topic drift, birth, etc. are also long term goals of interest. 

With respect to HDBSCAN, there is actually a better way to control the number of topics. Hierarchical topic reduction can be performed on the natural number of topics discovered. The benefit of this method is that there is a mapping between the reduced number of topics and natural number found. This is a feature that I will be adding in the coming weeks. 

The HDBSCAN min_cluster_size parameter when increased can actually lead to poor topics. This is because the low dimensional document vectors from UMAP, with too large a min_cluster_size can merge documents into a single cluster which are actually very distant in the original dimensional space. The hierarchical topic reduction is done in the original dimensional space and as a result works much better. It also finds the most prominent topics of the corpus.

I am currently working on a paper that explains a lot of this in much more detail. 

Cheers,

Dimo

**Comment by Benja1972** [comment]
Thank you! Waiting for update

**Comment by ddangelov** [comment]
@Benja1972 

I just added the hierarchical topic reduction feature. This will not be on pip until I get a chance to thoroughly test it and create documentation for it. However if you install from the repo you should be able to try it out. :)

**Comment by Benja1972** [comment]
@ddangelov 
Nice! Thank you, I will try and report you my feedback.

Keep a good project
