### ISSUE TITLE
Is a GPU allowed to train the model when setting speed="deep-learn"?

### ISSUE THREAD

**Issue by wmmxk** [ddangelov/Top2Vec#67]
When initiating a Topc2Vec model, I can choose speed='deep-learn". It seems that multiple cores are used but GPU-training is not allowed. To be honest, it is a little bit surprising to me that a GPU is not allowed when a deep learning model. But I think I missed something. Could you clarify on this?

**Comment by ddangelov** [comment]
When using `doc2vec` as `embedding_model` there is a multi-core option, no GPU. This is due to the Gensim implementation. When using the `universal-sentence-encoder` or `sentence-transformer` options which are Tensorflow and Pytorch, GPU can be utilized if all necessary libraries are installed. More info [here](https://github.com/ddangelov/Top2Vec#pretrained-models-). UMAP and HDBSCAN currently also do not utilize GPU. I would suggest reading the code and the paper if you want more details.
