### ISSUE TITLE
Handling out of vocabulary words

### ISSUE THREAD

**Issue by sanchez5674** [ddangelov/Top2Vec#74]
Hi, 

I can get the vocabulary words in the model and I could use FastText to look for the closest word (cosine similarity) in the vocabulary when my keyword does not exist. Would this be the "best" way to do it or is there a possibility to use the embeddings from the keyword to do the search? 

Thanks in advance. 

Carlos

**Comment by ddangelov** [comment]
Hi Carlos,

That sounds like a good idea.

It could be worth trying to look for the K-nearest words rather than just the nearest, to help smooth out differences between your corpus and the FastText corpus. You could even use the FastText similarity to do a weighted combination of the K nearest words, where nearer words get greater weight.

Alternatively if you use the `universal-sentence-encoder` or `sentence-transformer` `embedding_model` options they should be able to embed any vocabulary. This can be done with `top2vec._embed('OOV_word')`.
