### ISSUE TITLE
Vocab drops accents in French words for English/French corpus

### ISSUE THREAD

**Issue by sanchez5674** [ddangelov/Top2Vec#78]
Hi, 

I'm following your suggestion to use Top2Vec._embed("word") to handle out of vocabulary words and in the process complicating things a bit more since in my real use case I have a mixture of English and French documents. 

I'm training my Top2Vec model using the Universal Sentence Encoder. After the training is complete, I looked in the vocabulary, and for some reason, the accents on the French words are not preserved. For instance, the word "données" (data) is stored as "donnees". Why is that? Now the problem is twofold when I do a keyword search: (1) if I use "données" it complaints the word does not exist, and (2) if I use "donnees" the results don't really make sense as it returns documents related to jewelry so I don't know what is really happening. 

Thanks a lot for your help. 

Carlos

**Comment by ddangelov** [comment]
Hi Carlos,

The `universal-sentence-encoder-multilingual` should be able to handle English and French.

The accent removal is due to the default tokenizer, which removes accents by default:

https://github.com/ddangelov/Top2Vec/blob/9271bddf511a5ba1608c7a6efddc4cbe82659378/top2vec/Top2Vec.py#L45

When training you can pass a custom tokenizer function with the `tokenizer` parameter. Passing the following should prevent accents from being removed:

```python
from gensim.utils import simple_preprocess

def tokenizer(doc):
    """Tokenize documents for training and remove too long/short words"""
    return simple_preprocess(doc)
```

Additionally the `min_count` will remove any words with total number of occurrences in the corpus less than `min_count`, so this could also be removing words from your vocabulary.
